name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Shared Build Logic
        run: echo "Building app for environment:${{ inputs.environment_name }}"
